version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: synapse_server_1
      APP_PORT: $APP_SYNAPSE_PORT
      PROXY_AUTH_ADD: "false"

  server:
    image: ghcr.io/element-hq/synapse:v1.99.0@sha256:d67f79582f3dc053dfadb15c4c78b8f2623090da3c19fe60d3b6e66c65a7ca6f
#    user: "1000:1000" # doesn't work at the moment
    restart: on-failure
    stop_grace_period: 1m
    entrypoint: "bash"
    command: "-c './start.py generate && ./start.py migrate_config && exec ./start.py'"
    volumes:
      - ${APP_DATA_DIR}/data/synapse:/data
    environment:
#      UID: "1000" # doesn't work at the moment
#      GID: "1000" # doesn't work at the moment
      SYNAPSE_HTTP_PORT: "${APP_SYNAPSE_PORT}"
      SYNAPSE_SERVER_NAME: "${APP_HIDDEN_SERVICE}"
      SYNAPSE_REPORT_STATS: "yes"
      SYNAPSE_REGISTRATION_SHARED_SECRET: "itsbesttochangeit"
#      SYNAPSE_ENABLE_REGISTRATION: "yes"
      SYNAPSE_NO_TLS: "yes"
